/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/alert': RouteRecordInfo<'/alert', '/alert', Record<never, never>, Record<never, never>>,
    '/button': RouteRecordInfo<'/button', '/button', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/card': RouteRecordInfo<'/card', '/card', Record<never, never>, Record<never, never>>,
    '/cascader': RouteRecordInfo<'/cascader', '/cascader', Record<never, never>, Record<never, never>>,
    '/checkbox': RouteRecordInfo<'/checkbox', '/checkbox', Record<never, never>, Record<never, never>>,
    '/clock': RouteRecordInfo<'/clock', '/clock', Record<never, never>, Record<never, never>>,
    '/cloud': RouteRecordInfo<'/cloud', '/cloud', Record<never, never>, Record<never, never>>,
    '/colorPicker': RouteRecordInfo<'/colorPicker', '/colorPicker', Record<never, never>, Record<never, never>>,
    '/divider': RouteRecordInfo<'/divider', '/divider', Record<never, never>, Record<never, never>>,
    '/float': RouteRecordInfo<'/float', '/float', Record<never, never>, Record<never, never>>,
    '/icon': RouteRecordInfo<'/icon', '/icon', Record<never, never>, Record<never, never>>,
    '/input': RouteRecordInfo<'/input', '/input', Record<never, never>, Record<never, never>>,
    '/inputNumber': RouteRecordInfo<'/inputNumber', '/inputNumber', Record<never, never>, Record<never, never>>,
    '/layout': RouteRecordInfo<'/layout', '/layout', Record<never, never>, Record<never, never>>,
    '/link': RouteRecordInfo<'/link', '/link', Record<never, never>, Record<never, never>>,
    '/loading': RouteRecordInfo<'/loading', '/loading', Record<never, never>, Record<never, never>>,
    '/menu': RouteRecordInfo<'/menu', '/menu', Record<never, never>, Record<never, never>>,
    '/preLoading': RouteRecordInfo<'/preLoading', '/preLoading', Record<never, never>, Record<never, never>>,
    '/progress': RouteRecordInfo<'/progress', '/progress', Record<never, never>, Record<never, never>>,
    '/radio': RouteRecordInfo<'/radio', '/radio', Record<never, never>, Record<never, never>>,
    '/rate': RouteRecordInfo<'/rate', '/rate', Record<never, never>, Record<never, never>>,
    '/scroller': RouteRecordInfo<'/scroller', '/scroller', Record<never, never>, Record<never, never>>,
    '/select': RouteRecordInfo<'/select', '/select', Record<never, never>, Record<never, never>>,
    '/slider': RouteRecordInfo<'/slider', '/slider', Record<never, never>, Record<never, never>>,
    '/step': RouteRecordInfo<'/step', '/step', Record<never, never>, Record<never, never>>,
    '/switch': RouteRecordInfo<'/switch', '/switch', Record<never, never>, Record<never, never>>,
    '/tab': RouteRecordInfo<'/tab', '/tab', Record<never, never>, Record<never, never>>,
    '/upload': RouteRecordInfo<'/upload', '/upload', Record<never, never>, Record<never, never>>,
    '/waterDroplet': RouteRecordInfo<'/waterDroplet', '/waterDroplet', Record<never, never>, Record<never, never>>,
  }
}
